use_frameworks!

platform :ios, '10.0'

target 'MFCycleView_Example' do
  pod 'MFCycleView', :path => '../'

  target 'MFCycleView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
